-- ============================================
-- ScriptHub.id Database Schema - Key System Module
-- Version: 015
-- Description: Create license_keys, key_devices, and key_settings tables
-- ============================================

-- ============================================
-- ENUM TYPES
-- ============================================
DO $$ BEGIN
    CREATE TYPE key_type AS ENUM ('lifetime', 'timed', 'device_locked');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE key_status AS ENUM ('active', 'expired', 'revoked', 'unused');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================
-- LICENSE KEYS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS license_keys (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    key_value VARCHAR(32) NOT NULL UNIQUE,
    script_id UUID NOT NULL REFERENCES scripts(id) ON DELETE CASCADE,
    owner_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type key_type NOT NULL DEFAULT 'lifetime',
    status key_status NOT NULL DEFAULT 'unused',
    max_devices INT NOT NULL DEFAULT 1,
    expires_at TIMESTAMP WITH TIME ZONE,
    note TEXT,
    last_activity_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_license_keys_owner_id ON license_keys(owner_id);
CREATE INDEX IF NOT EXISTS idx_license_keys_script_id ON license_keys(script_id);
CREATE INDEX IF NOT EXISTS idx_license_keys_status ON license_keys(status);
CREATE INDEX IF NOT EXISTS idx_license_keys_key_value ON license_keys(key_value);
CREATE INDEX IF NOT EXISTS idx_license_keys_created_at ON license_keys(created_at DESC);

-- Trigger for updated_at
CREATE TRIGGER update_license_keys_updated_at BEFORE UPDATE ON license_keys
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE license_keys IS 'License keys generated by script owners for access control';

-- ============================================
-- KEY DEVICES TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS key_devices (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    key_id UUID NOT NULL REFERENCES license_keys(id) ON DELETE CASCADE,
    hwid VARCHAR(128) NOT NULL,
    ip_address VARCHAR(45),
    first_seen_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_key_devices_key_id ON key_devices(key_id);
CREATE INDEX IF NOT EXISTS idx_key_devices_hwid ON key_devices(hwid);

-- Unique constraint: one HWID per key
CREATE UNIQUE INDEX IF NOT EXISTS idx_key_devices_key_hwid ON key_devices(key_id, hwid);

COMMENT ON TABLE key_devices IS 'Devices bound to license keys via HWID';

-- ============================================
-- KEY SETTINGS TABLE (per-user config)
-- ============================================
CREATE TABLE IF NOT EXISTS key_settings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    device_lock_enabled BOOLEAN NOT NULL DEFAULT true,
    max_devices_per_key INT NOT NULL DEFAULT 3,
    rate_limiting_enabled BOOLEAN NOT NULL DEFAULT true,
    auto_expire_enabled BOOLEAN NOT NULL DEFAULT false,
    hwid_blacklist_enabled BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Trigger for updated_at
CREATE TRIGGER update_key_settings_updated_at BEFORE UPDATE ON key_settings
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE key_settings IS 'Per-user security configuration for the key system';
